name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  compile-test-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
      - name: Install project dependencies
        uses: docker://dataformco/dataform:latest
        with:
          args: install
      - name: Generate Dataform credentials
        run: |
          echo "${{ secrets.DATAFORM_KEY }}" > .df-credentials.json
      - name: Compile
        uses: docker://dataformco/dataform:latest
        with:
          args: compile
      - name: Dry run
        uses: docker://dataformco/dataform:latest
        with:
          args: run --dry-run